name: Build Docker Container
on: [workflow_dispatch]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: export requirements with poetry
        uses: divideprojects/poetry-export-requirements-action@v1
        with:
          without-hashes: true
          outfile-name: requirements.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/felix920506/jellychord:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7